apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: dev
spec:
  limits:
  - default:
      cpu: 0.5
      memory: 512Mi
    defaultRequest:
      cpu: 0.25
      memory: 256Mi
    max:
      cpu: 1
      memory: 1Gi
    min:
      cpu: 200m
      memory: 256Mi
    type: Container
  - max:
      storage: 2Gi
    min:
      storage: 1Gi
    type: PersistentVolumeClaim
