kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: small
  name: pod-and-pod-logs-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: small
  name: small-pod-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-and-pod-logs-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: "$READER_USER_ID"