kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev
  name: deployment-manager
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: dev-deployment-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-manager
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: "$DEPLOYMENT_USER_ID"
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "$DEPLOYMENT_GROUP_ID"